apiVersion: v1
kind: Service
metadata:
  name: front-entrenapp-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: front-entrenapp
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
